---
go:
  - 1.10
python:
  - 2.7

services: docker

env:
  - distro: ubuntu1604
  - distro: ubuntu1804
  - distro: centos7
  - distro: debian10

before_install:
  - go get -v github.com/fubarhouse/ansible-role-tester

script:
  - ansible-role-tester full --distribution ${distro} --destination /etc/ansible/roles/$(basename $(pwd)) 

# rerun test with verbose logs
after_failure:
  - ansible-role-tester full --distribution ${distro} --destination /etc/ansible/roles/$(basename $(pwd)) --verbose
  
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
