---
language: go
install: true # https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
sudo: false

# Only clone the most recent commit.
git:
  depth: 1

go:
  - 1.x
python:
  - 2.7

services: docker

addons:
  apt:
    packages:
      - curl
      - jq

env:
  - distro: ubuntu1604
  - distro: ubuntu1804
  - distro: centos7
  - distro: debian10

before_install:
  - go get -v github.com/fubarhouse/ansible-role-tester
  - U=$(curl https://github.cache.smirnov.cloud/repos/sharkdp/bat/releases/latest | jq -r -c 'first(.assets[] | select(.browser_download_url | contains("amd64"))) | .browser_download_url')
  - wget $U # download bat.deb
  - sudo dpkg -i $(basename $U) # install bat.

script:
  - ansible-role-tester full --distribution ${distro} --destination /etc/ansible/roles/$(basename $(pwd)) 

# rerun test with verbose logs
after_failure:
  - ansible-role-tester full --distribution ${distro} --destination /etc/ansible/roles/$(basename $(pwd)) --verbose
  
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
